// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package cmessage;

public final class User {
  private User() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface userOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cmessage.user)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 status = 1;</code>
     */
    int getStatus();

    /**
     * <code>int64 id = 3;</code>
     */
    long getId();

    /**
     * <code>string response = 2;</code>
     */
    java.lang.String getResponse();
    /**
     * <code>string response = 2;</code>
     */
    com.google.protobuf.ByteString
        getResponseBytes();

    /**
     * <code>int64 fid = 36;</code>
     */
    long getFid();

    /**
     * <code>int64 fid2 = 37;</code>
     */
    long getFid2();

    /**
     * <code>string uuid = 4;</code>
     */
    java.lang.String getUuid();
    /**
     * <code>string uuid = 4;</code>
     */
    com.google.protobuf.ByteString
        getUuidBytes();

    /**
     * <code>string account = 33;</code>
     */
    java.lang.String getAccount();
    /**
     * <code>string account = 33;</code>
     */
    com.google.protobuf.ByteString
        getAccountBytes();

    /**
     * <pre>
     *    ACCOUNT_FIELD_NUMBER = 0x21;
     *    AVATAR_FIELD_NUMBER = 0x6;
     *    BIRTHCITYID_FIELD_NUMBER = 0x10;
     *    BIRTHDAY_FIELD_NUMBER = 0xf;
     *    CARRIERCITYID_FIELD_NUMBER = 0x1c;
     *    CARRIER_FIELD_NUMBER = 0x1b;
     *    CODE_FIELD_NUMBER = 0x23;
     *    COVERURL_FIELD_NUMBER = 0x11;
     *    DEPARTMENTID_FIELD_NUMBER = 0xc;
     *    DEPARTMENT_FIELD_NUMBER = 0xd;
     *    DID_FIELD_NUMBER = 0x1a;
     *    FID2_FIELD_NUMBER = 0x25;
     *    FID_FIELD_NUMBER = 0x24;
     *    FOLLOWVERSION_FIELD_NUMBER = 0x13;
     *    GENDER_FIELD_NUMBER = 0x7;
     *    ID_FIELD_NUMBER = 0x3;
     *    ISSILENCE_FIELD_NUMBER = 0x26;
     *    MOBILE_FIELD_NUMBER = 0x19;
     *    NAME_FIELD_NUMBER = 0x5;
     *    PASSWORD_FIELD_NUMBER = 0x22;
     *    PRIVILEGE_FIELD_NUMBER = 0x15;
     *    RESPONSE_FIELD_NUMBER = 0x2;
     *    ROLENAME_FIELD_NUMBER = 0x18;
     *    ROLE_FIELD_NUMBER = 0x17;
     *    SCHOOLID_FIELD_NUMBER = 0xa;
     *    SCHOOL_FIELD_NUMBER = 0xb;
     *    SIGNATURE_FIELD_NUMBER = 0x12;
     *    STATUS_FIELD_NUMBER = 0x1;
     *    TIME_FIELD_NUMBER = 0x1d;
     *    USERSTATS_FIELD_NUMBER = 0x14;
     *    UUID_FIELD_NUMBER = 0x4;
     *    VERIFYSTATE_FIELD_NUMBER = 0x8;
     *    VERIFYTITLE_FIELD_NUMBER = 0x9;
     *    WIFIURL_FIELD_NUMBER = 0x16;
     *    YEAR_FIELD_NUMBER = 0xe;
     * </pre>
     *
     * <code>int32 follow_version = 19;</code>
     */
    int getFollowVersion();
  }
  /**
   * Protobuf type {@code cmessage.user}
   */
  public  static final class user extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:cmessage.user)
      userOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use user.newBuilder() to construct.
    private user(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private user() {
      status_ = 0;
      id_ = 0L;
      response_ = "";
      fid_ = 0L;
      fid2_ = 0L;
      uuid_ = "";
      account_ = "";
      followVersion_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private user(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              status_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              response_ = s;
              break;
            }
            case 24: {

              id_ = input.readInt64();
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              uuid_ = s;
              break;
            }
            case 152: {

              followVersion_ = input.readInt32();
              break;
            }
            case 266: {
              java.lang.String s = input.readStringRequireUtf8();

              account_ = s;
              break;
            }
            case 288: {

              fid_ = input.readInt64();
              break;
            }
            case 296: {

              fid2_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cmessage.User.internal_static_cmessage_user_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cmessage.User.internal_static_cmessage_user_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cmessage.User.user.class, cmessage.User.user.Builder.class);
    }

    public static final int STATUS_FIELD_NUMBER = 1;
    private int status_;
    /**
     * <code>int32 status = 1;</code>
     */
    public int getStatus() {
      return status_;
    }

    public static final int ID_FIELD_NUMBER = 3;
    private long id_;
    /**
     * <code>int64 id = 3;</code>
     */
    public long getId() {
      return id_;
    }

    public static final int RESPONSE_FIELD_NUMBER = 2;
    private volatile java.lang.Object response_;
    /**
     * <code>string response = 2;</code>
     */
    public java.lang.String getResponse() {
      java.lang.Object ref = response_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        response_ = s;
        return s;
      }
    }
    /**
     * <code>string response = 2;</code>
     */
    public com.google.protobuf.ByteString
        getResponseBytes() {
      java.lang.Object ref = response_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        response_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FID_FIELD_NUMBER = 36;
    private long fid_;
    /**
     * <code>int64 fid = 36;</code>
     */
    public long getFid() {
      return fid_;
    }

    public static final int FID2_FIELD_NUMBER = 37;
    private long fid2_;
    /**
     * <code>int64 fid2 = 37;</code>
     */
    public long getFid2() {
      return fid2_;
    }

    public static final int UUID_FIELD_NUMBER = 4;
    private volatile java.lang.Object uuid_;
    /**
     * <code>string uuid = 4;</code>
     */
    public java.lang.String getUuid() {
      java.lang.Object ref = uuid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        uuid_ = s;
        return s;
      }
    }
    /**
     * <code>string uuid = 4;</code>
     */
    public com.google.protobuf.ByteString
        getUuidBytes() {
      java.lang.Object ref = uuid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uuid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ACCOUNT_FIELD_NUMBER = 33;
    private volatile java.lang.Object account_;
    /**
     * <code>string account = 33;</code>
     */
    public java.lang.String getAccount() {
      java.lang.Object ref = account_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        account_ = s;
        return s;
      }
    }
    /**
     * <code>string account = 33;</code>
     */
    public com.google.protobuf.ByteString
        getAccountBytes() {
      java.lang.Object ref = account_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        account_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FOLLOW_VERSION_FIELD_NUMBER = 19;
    private int followVersion_;
    /**
     * <pre>
     *    ACCOUNT_FIELD_NUMBER = 0x21;
     *    AVATAR_FIELD_NUMBER = 0x6;
     *    BIRTHCITYID_FIELD_NUMBER = 0x10;
     *    BIRTHDAY_FIELD_NUMBER = 0xf;
     *    CARRIERCITYID_FIELD_NUMBER = 0x1c;
     *    CARRIER_FIELD_NUMBER = 0x1b;
     *    CODE_FIELD_NUMBER = 0x23;
     *    COVERURL_FIELD_NUMBER = 0x11;
     *    DEPARTMENTID_FIELD_NUMBER = 0xc;
     *    DEPARTMENT_FIELD_NUMBER = 0xd;
     *    DID_FIELD_NUMBER = 0x1a;
     *    FID2_FIELD_NUMBER = 0x25;
     *    FID_FIELD_NUMBER = 0x24;
     *    FOLLOWVERSION_FIELD_NUMBER = 0x13;
     *    GENDER_FIELD_NUMBER = 0x7;
     *    ID_FIELD_NUMBER = 0x3;
     *    ISSILENCE_FIELD_NUMBER = 0x26;
     *    MOBILE_FIELD_NUMBER = 0x19;
     *    NAME_FIELD_NUMBER = 0x5;
     *    PASSWORD_FIELD_NUMBER = 0x22;
     *    PRIVILEGE_FIELD_NUMBER = 0x15;
     *    RESPONSE_FIELD_NUMBER = 0x2;
     *    ROLENAME_FIELD_NUMBER = 0x18;
     *    ROLE_FIELD_NUMBER = 0x17;
     *    SCHOOLID_FIELD_NUMBER = 0xa;
     *    SCHOOL_FIELD_NUMBER = 0xb;
     *    SIGNATURE_FIELD_NUMBER = 0x12;
     *    STATUS_FIELD_NUMBER = 0x1;
     *    TIME_FIELD_NUMBER = 0x1d;
     *    USERSTATS_FIELD_NUMBER = 0x14;
     *    UUID_FIELD_NUMBER = 0x4;
     *    VERIFYSTATE_FIELD_NUMBER = 0x8;
     *    VERIFYTITLE_FIELD_NUMBER = 0x9;
     *    WIFIURL_FIELD_NUMBER = 0x16;
     *    YEAR_FIELD_NUMBER = 0xe;
     * </pre>
     *
     * <code>int32 follow_version = 19;</code>
     */
    public int getFollowVersion() {
      return followVersion_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (status_ != 0) {
        output.writeInt32(1, status_);
      }
      if (!getResponseBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, response_);
      }
      if (id_ != 0L) {
        output.writeInt64(3, id_);
      }
      if (!getUuidBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, uuid_);
      }
      if (followVersion_ != 0) {
        output.writeInt32(19, followVersion_);
      }
      if (!getAccountBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 33, account_);
      }
      if (fid_ != 0L) {
        output.writeInt64(36, fid_);
      }
      if (fid2_ != 0L) {
        output.writeInt64(37, fid2_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (status_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, status_);
      }
      if (!getResponseBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, response_);
      }
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, id_);
      }
      if (!getUuidBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, uuid_);
      }
      if (followVersion_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(19, followVersion_);
      }
      if (!getAccountBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(33, account_);
      }
      if (fid_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(36, fid_);
      }
      if (fid2_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(37, fid2_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cmessage.User.user)) {
        return super.equals(obj);
      }
      cmessage.User.user other = (cmessage.User.user) obj;

      boolean result = true;
      result = result && (getStatus()
          == other.getStatus());
      result = result && (getId()
          == other.getId());
      result = result && getResponse()
          .equals(other.getResponse());
      result = result && (getFid()
          == other.getFid());
      result = result && (getFid2()
          == other.getFid2());
      result = result && getUuid()
          .equals(other.getUuid());
      result = result && getAccount()
          .equals(other.getAccount());
      result = result && (getFollowVersion()
          == other.getFollowVersion());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + getStatus();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (37 * hash) + RESPONSE_FIELD_NUMBER;
      hash = (53 * hash) + getResponse().hashCode();
      hash = (37 * hash) + FID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getFid());
      hash = (37 * hash) + FID2_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getFid2());
      hash = (37 * hash) + UUID_FIELD_NUMBER;
      hash = (53 * hash) + getUuid().hashCode();
      hash = (37 * hash) + ACCOUNT_FIELD_NUMBER;
      hash = (53 * hash) + getAccount().hashCode();
      hash = (37 * hash) + FOLLOW_VERSION_FIELD_NUMBER;
      hash = (53 * hash) + getFollowVersion();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cmessage.User.user parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cmessage.User.user parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cmessage.User.user parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cmessage.User.user parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cmessage.User.user parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cmessage.User.user parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cmessage.User.user parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cmessage.User.user parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cmessage.User.user parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cmessage.User.user parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cmessage.User.user parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cmessage.User.user parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cmessage.User.user prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code cmessage.user}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cmessage.user)
        cmessage.User.userOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cmessage.User.internal_static_cmessage_user_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cmessage.User.internal_static_cmessage_user_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cmessage.User.user.class, cmessage.User.user.Builder.class);
      }

      // Construct using cmessage.User.user.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        status_ = 0;

        id_ = 0L;

        response_ = "";

        fid_ = 0L;

        fid2_ = 0L;

        uuid_ = "";

        account_ = "";

        followVersion_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cmessage.User.internal_static_cmessage_user_descriptor;
      }

      public cmessage.User.user getDefaultInstanceForType() {
        return cmessage.User.user.getDefaultInstance();
      }

      public cmessage.User.user build() {
        cmessage.User.user result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cmessage.User.user buildPartial() {
        cmessage.User.user result = new cmessage.User.user(this);
        result.status_ = status_;
        result.id_ = id_;
        result.response_ = response_;
        result.fid_ = fid_;
        result.fid2_ = fid2_;
        result.uuid_ = uuid_;
        result.account_ = account_;
        result.followVersion_ = followVersion_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cmessage.User.user) {
          return mergeFrom((cmessage.User.user)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cmessage.User.user other) {
        if (other == cmessage.User.user.getDefaultInstance()) return this;
        if (other.getStatus() != 0) {
          setStatus(other.getStatus());
        }
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        if (!other.getResponse().isEmpty()) {
          response_ = other.response_;
          onChanged();
        }
        if (other.getFid() != 0L) {
          setFid(other.getFid());
        }
        if (other.getFid2() != 0L) {
          setFid2(other.getFid2());
        }
        if (!other.getUuid().isEmpty()) {
          uuid_ = other.uuid_;
          onChanged();
        }
        if (!other.getAccount().isEmpty()) {
          account_ = other.account_;
          onChanged();
        }
        if (other.getFollowVersion() != 0) {
          setFollowVersion(other.getFollowVersion());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cmessage.User.user parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cmessage.User.user) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int status_ ;
      /**
       * <code>int32 status = 1;</code>
       */
      public int getStatus() {
        return status_;
      }
      /**
       * <code>int32 status = 1;</code>
       */
      public Builder setStatus(int value) {
        
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 status = 1;</code>
       */
      public Builder clearStatus() {
        
        status_ = 0;
        onChanged();
        return this;
      }

      private long id_ ;
      /**
       * <code>int64 id = 3;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>int64 id = 3;</code>
       */
      public Builder setId(long value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 id = 3;</code>
       */
      public Builder clearId() {
        
        id_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object response_ = "";
      /**
       * <code>string response = 2;</code>
       */
      public java.lang.String getResponse() {
        java.lang.Object ref = response_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          response_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string response = 2;</code>
       */
      public com.google.protobuf.ByteString
          getResponseBytes() {
        java.lang.Object ref = response_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          response_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string response = 2;</code>
       */
      public Builder setResponse(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        response_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string response = 2;</code>
       */
      public Builder clearResponse() {
        
        response_ = getDefaultInstance().getResponse();
        onChanged();
        return this;
      }
      /**
       * <code>string response = 2;</code>
       */
      public Builder setResponseBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        response_ = value;
        onChanged();
        return this;
      }

      private long fid_ ;
      /**
       * <code>int64 fid = 36;</code>
       */
      public long getFid() {
        return fid_;
      }
      /**
       * <code>int64 fid = 36;</code>
       */
      public Builder setFid(long value) {
        
        fid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 fid = 36;</code>
       */
      public Builder clearFid() {
        
        fid_ = 0L;
        onChanged();
        return this;
      }

      private long fid2_ ;
      /**
       * <code>int64 fid2 = 37;</code>
       */
      public long getFid2() {
        return fid2_;
      }
      /**
       * <code>int64 fid2 = 37;</code>
       */
      public Builder setFid2(long value) {
        
        fid2_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 fid2 = 37;</code>
       */
      public Builder clearFid2() {
        
        fid2_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object uuid_ = "";
      /**
       * <code>string uuid = 4;</code>
       */
      public java.lang.String getUuid() {
        java.lang.Object ref = uuid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          uuid_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string uuid = 4;</code>
       */
      public com.google.protobuf.ByteString
          getUuidBytes() {
        java.lang.Object ref = uuid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          uuid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string uuid = 4;</code>
       */
      public Builder setUuid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        uuid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string uuid = 4;</code>
       */
      public Builder clearUuid() {
        
        uuid_ = getDefaultInstance().getUuid();
        onChanged();
        return this;
      }
      /**
       * <code>string uuid = 4;</code>
       */
      public Builder setUuidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        uuid_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object account_ = "";
      /**
       * <code>string account = 33;</code>
       */
      public java.lang.String getAccount() {
        java.lang.Object ref = account_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          account_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string account = 33;</code>
       */
      public com.google.protobuf.ByteString
          getAccountBytes() {
        java.lang.Object ref = account_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          account_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string account = 33;</code>
       */
      public Builder setAccount(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        account_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string account = 33;</code>
       */
      public Builder clearAccount() {
        
        account_ = getDefaultInstance().getAccount();
        onChanged();
        return this;
      }
      /**
       * <code>string account = 33;</code>
       */
      public Builder setAccountBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        account_ = value;
        onChanged();
        return this;
      }

      private int followVersion_ ;
      /**
       * <pre>
       *    ACCOUNT_FIELD_NUMBER = 0x21;
       *    AVATAR_FIELD_NUMBER = 0x6;
       *    BIRTHCITYID_FIELD_NUMBER = 0x10;
       *    BIRTHDAY_FIELD_NUMBER = 0xf;
       *    CARRIERCITYID_FIELD_NUMBER = 0x1c;
       *    CARRIER_FIELD_NUMBER = 0x1b;
       *    CODE_FIELD_NUMBER = 0x23;
       *    COVERURL_FIELD_NUMBER = 0x11;
       *    DEPARTMENTID_FIELD_NUMBER = 0xc;
       *    DEPARTMENT_FIELD_NUMBER = 0xd;
       *    DID_FIELD_NUMBER = 0x1a;
       *    FID2_FIELD_NUMBER = 0x25;
       *    FID_FIELD_NUMBER = 0x24;
       *    FOLLOWVERSION_FIELD_NUMBER = 0x13;
       *    GENDER_FIELD_NUMBER = 0x7;
       *    ID_FIELD_NUMBER = 0x3;
       *    ISSILENCE_FIELD_NUMBER = 0x26;
       *    MOBILE_FIELD_NUMBER = 0x19;
       *    NAME_FIELD_NUMBER = 0x5;
       *    PASSWORD_FIELD_NUMBER = 0x22;
       *    PRIVILEGE_FIELD_NUMBER = 0x15;
       *    RESPONSE_FIELD_NUMBER = 0x2;
       *    ROLENAME_FIELD_NUMBER = 0x18;
       *    ROLE_FIELD_NUMBER = 0x17;
       *    SCHOOLID_FIELD_NUMBER = 0xa;
       *    SCHOOL_FIELD_NUMBER = 0xb;
       *    SIGNATURE_FIELD_NUMBER = 0x12;
       *    STATUS_FIELD_NUMBER = 0x1;
       *    TIME_FIELD_NUMBER = 0x1d;
       *    USERSTATS_FIELD_NUMBER = 0x14;
       *    UUID_FIELD_NUMBER = 0x4;
       *    VERIFYSTATE_FIELD_NUMBER = 0x8;
       *    VERIFYTITLE_FIELD_NUMBER = 0x9;
       *    WIFIURL_FIELD_NUMBER = 0x16;
       *    YEAR_FIELD_NUMBER = 0xe;
       * </pre>
       *
       * <code>int32 follow_version = 19;</code>
       */
      public int getFollowVersion() {
        return followVersion_;
      }
      /**
       * <pre>
       *    ACCOUNT_FIELD_NUMBER = 0x21;
       *    AVATAR_FIELD_NUMBER = 0x6;
       *    BIRTHCITYID_FIELD_NUMBER = 0x10;
       *    BIRTHDAY_FIELD_NUMBER = 0xf;
       *    CARRIERCITYID_FIELD_NUMBER = 0x1c;
       *    CARRIER_FIELD_NUMBER = 0x1b;
       *    CODE_FIELD_NUMBER = 0x23;
       *    COVERURL_FIELD_NUMBER = 0x11;
       *    DEPARTMENTID_FIELD_NUMBER = 0xc;
       *    DEPARTMENT_FIELD_NUMBER = 0xd;
       *    DID_FIELD_NUMBER = 0x1a;
       *    FID2_FIELD_NUMBER = 0x25;
       *    FID_FIELD_NUMBER = 0x24;
       *    FOLLOWVERSION_FIELD_NUMBER = 0x13;
       *    GENDER_FIELD_NUMBER = 0x7;
       *    ID_FIELD_NUMBER = 0x3;
       *    ISSILENCE_FIELD_NUMBER = 0x26;
       *    MOBILE_FIELD_NUMBER = 0x19;
       *    NAME_FIELD_NUMBER = 0x5;
       *    PASSWORD_FIELD_NUMBER = 0x22;
       *    PRIVILEGE_FIELD_NUMBER = 0x15;
       *    RESPONSE_FIELD_NUMBER = 0x2;
       *    ROLENAME_FIELD_NUMBER = 0x18;
       *    ROLE_FIELD_NUMBER = 0x17;
       *    SCHOOLID_FIELD_NUMBER = 0xa;
       *    SCHOOL_FIELD_NUMBER = 0xb;
       *    SIGNATURE_FIELD_NUMBER = 0x12;
       *    STATUS_FIELD_NUMBER = 0x1;
       *    TIME_FIELD_NUMBER = 0x1d;
       *    USERSTATS_FIELD_NUMBER = 0x14;
       *    UUID_FIELD_NUMBER = 0x4;
       *    VERIFYSTATE_FIELD_NUMBER = 0x8;
       *    VERIFYTITLE_FIELD_NUMBER = 0x9;
       *    WIFIURL_FIELD_NUMBER = 0x16;
       *    YEAR_FIELD_NUMBER = 0xe;
       * </pre>
       *
       * <code>int32 follow_version = 19;</code>
       */
      public Builder setFollowVersion(int value) {
        
        followVersion_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *    ACCOUNT_FIELD_NUMBER = 0x21;
       *    AVATAR_FIELD_NUMBER = 0x6;
       *    BIRTHCITYID_FIELD_NUMBER = 0x10;
       *    BIRTHDAY_FIELD_NUMBER = 0xf;
       *    CARRIERCITYID_FIELD_NUMBER = 0x1c;
       *    CARRIER_FIELD_NUMBER = 0x1b;
       *    CODE_FIELD_NUMBER = 0x23;
       *    COVERURL_FIELD_NUMBER = 0x11;
       *    DEPARTMENTID_FIELD_NUMBER = 0xc;
       *    DEPARTMENT_FIELD_NUMBER = 0xd;
       *    DID_FIELD_NUMBER = 0x1a;
       *    FID2_FIELD_NUMBER = 0x25;
       *    FID_FIELD_NUMBER = 0x24;
       *    FOLLOWVERSION_FIELD_NUMBER = 0x13;
       *    GENDER_FIELD_NUMBER = 0x7;
       *    ID_FIELD_NUMBER = 0x3;
       *    ISSILENCE_FIELD_NUMBER = 0x26;
       *    MOBILE_FIELD_NUMBER = 0x19;
       *    NAME_FIELD_NUMBER = 0x5;
       *    PASSWORD_FIELD_NUMBER = 0x22;
       *    PRIVILEGE_FIELD_NUMBER = 0x15;
       *    RESPONSE_FIELD_NUMBER = 0x2;
       *    ROLENAME_FIELD_NUMBER = 0x18;
       *    ROLE_FIELD_NUMBER = 0x17;
       *    SCHOOLID_FIELD_NUMBER = 0xa;
       *    SCHOOL_FIELD_NUMBER = 0xb;
       *    SIGNATURE_FIELD_NUMBER = 0x12;
       *    STATUS_FIELD_NUMBER = 0x1;
       *    TIME_FIELD_NUMBER = 0x1d;
       *    USERSTATS_FIELD_NUMBER = 0x14;
       *    UUID_FIELD_NUMBER = 0x4;
       *    VERIFYSTATE_FIELD_NUMBER = 0x8;
       *    VERIFYTITLE_FIELD_NUMBER = 0x9;
       *    WIFIURL_FIELD_NUMBER = 0x16;
       *    YEAR_FIELD_NUMBER = 0xe;
       * </pre>
       *
       * <code>int32 follow_version = 19;</code>
       */
      public Builder clearFollowVersion() {
        
        followVersion_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:cmessage.user)
    }

    // @@protoc_insertion_point(class_scope:cmessage.user)
    private static final cmessage.User.user DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cmessage.User.user();
    }

    public static cmessage.User.user getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<user>
        PARSER = new com.google.protobuf.AbstractParser<user>() {
      public user parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new user(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<user> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<user> getParserForType() {
      return PARSER;
    }

    public cmessage.User.user getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cmessage_user_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cmessage_user_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nuser.proto\022\010cmessage\"\206\001\n\004user\022\016\n\006statu" +
      "s\030\001 \001(\005\022\n\n\002id\030\003 \001(\003\022\020\n\010response\030\002 \001(\t\022\013\n" +
      "\003fid\030$ \001(\003\022\014\n\004fid2\030% \001(\003\022\014\n\004uuid\030\004 \001(\t\022\017" +
      "\n\007account\030! \001(\t\022\026\n\016follow_version\030\023 \001(\005b" +
      "\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_cmessage_user_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_cmessage_user_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cmessage_user_descriptor,
        new java.lang.String[] { "Status", "Id", "Response", "Fid", "Fid2", "Uuid", "Account", "FollowVersion", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
