// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package cmessage

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type User struct {
	Status               int32    `protobuf:"varint,1,opt,name=status" json:"status,omitempty"`
	Id                   int64    `protobuf:"varint,3,opt,name=id" json:"id,omitempty"`
	Response             string   `protobuf:"bytes,2,opt,name=response" json:"response,omitempty"`
	Fid                  int64    `protobuf:"varint,36,opt,name=fid" json:"fid,omitempty"`
	Fid2                 int64    `protobuf:"varint,37,opt,name=fid2" json:"fid2,omitempty"`
	Uuid                 string   `protobuf:"bytes,4,opt,name=uuid" json:"uuid,omitempty"`
	Account              string   `protobuf:"bytes,33,opt,name=account" json:"account,omitempty"`
	FollowVersion        int32    `protobuf:"varint,19,opt,name=follow_version,json=followVersion" json:"follow_version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_88b50fb4912753c6, []int{0}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (dst *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(dst, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *User) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetResponse() string {
	if m != nil {
		return m.Response
	}
	return ""
}

func (m *User) GetFid() int64 {
	if m != nil {
		return m.Fid
	}
	return 0
}

func (m *User) GetFid2() int64 {
	if m != nil {
		return m.Fid2
	}
	return 0
}

func (m *User) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *User) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *User) GetFollowVersion() int32 {
	if m != nil {
		return m.FollowVersion
	}
	return 0
}

func init() {
	proto.RegisterType((*User)(nil), "cmessage.user")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_user_88b50fb4912753c6) }

var fileDescriptor_user_88b50fb4912753c6 = []byte{
	// 190 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0x8f, 0xc1, 0x6a, 0x83, 0x40,
	0x10, 0x40, 0x59, 0xb5, 0xd6, 0x0e, 0x54, 0xca, 0x14, 0xca, 0xd0, 0x93, 0x2d, 0x15, 0x3c, 0xf5,
	0x90, 0xfc, 0x89, 0x87, 0x5c, 0x83, 0x71, 0xd7, 0xb0, 0x60, 0x5c, 0xd9, 0xd9, 0x4d, 0xbe, 0x30,
	0xff, 0x15, 0x1c, 0x93, 0xdc, 0xde, 0x7b, 0xbb, 0x03, 0x33, 0x00, 0x91, 0x8d, 0xff, 0x9f, 0xbd,
	0x0b, 0x0e, 0x8b, 0xfe, 0x64, 0x98, 0xbb, 0xa3, 0xf9, 0xbd, 0x2a, 0xc8, 0x96, 0x07, 0xfc, 0x82,
	0x9c, 0x43, 0x17, 0x22, 0x93, 0xaa, 0x54, 0xf3, 0xd2, 0xde, 0x0d, 0x4b, 0x48, 0xac, 0xa6, 0xb4,
	0x52, 0x4d, 0xda, 0x26, 0x56, 0xe3, 0x37, 0x14, 0xde, 0xf0, 0xec, 0x26, 0x36, 0x94, 0x54, 0xaa,
	0x79, 0x6b, 0x9f, 0x8e, 0x1f, 0x90, 0x0e, 0x56, 0xd3, 0x9f, 0x7c, 0x5e, 0x10, 0x11, 0xb2, 0xc1,
	0xea, 0x0d, 0xd5, 0x92, 0x84, 0x97, 0x16, 0xa3, 0xd5, 0x94, 0xc9, 0xb4, 0x30, 0x12, 0xbc, 0x76,
	0x7d, 0xef, 0xe2, 0x14, 0xe8, 0x47, 0xf2, 0x43, 0xb1, 0x86, 0x72, 0x70, 0xe3, 0xe8, 0x2e, 0xfb,
	0xb3, 0xf1, 0x6c, 0xdd, 0x44, 0x9f, 0xb2, 0xdf, 0xfb, 0x5a, 0x77, 0x6b, 0x3c, 0xe4, 0x72, 0xd8,
	0xf6, 0x16, 0x00, 0x00, 0xff, 0xff, 0xd5, 0x10, 0xb5, 0x83, 0xe6, 0x00, 0x00, 0x00,
}
